# Generated by Django 4.1.7 on 2023-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
