# Generated by Django 4.1.7 on 2023-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_car_marka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Assign one of the pictures as a main one.', verbose_name='Main picture'),
        ),
    ]
